In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from astropy import units as u 
from astropy import constants as const 

plt.rcParams["figure.figsize"] = (6, 4)
plt.rcParams["figure.dpi"] = 120

In [2]:
csv_path = "solar_system.csv"
df = pd.read_csv(csv_path)

print("Original DataFrame shape:"   , df.shape) 
display(df.head())

Original DataFrame shape: (20, 11)

,Attribute,Mercury,Venus,Earth,Moon,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto
0,Mass (10^24kg),0.330,4.87,5.97,0.073,0.642,1898,568,86.8,102,0.0130
1,Diameter (km),4879,12104,12756,3475,6792,142984,120536,51118,49528,2376
2,Density (kg/m^3),5429,5243,5514,3340,3934,1326,687,1270,1638,1850
3,Gravity (m/s^2),3.7,8.9,9.8,1.6,3.7,23.1,9.0,8.7,11.0,0.7
4,Escape Velocity (km/s),4.3,10.4,11.2,2.4,5.0,59.5,35.5,21.3,23.5,1.3

In [3]:
# Cell 4: transpose the DataFrame so rows become planets instead of attributes

# Save shape BEFORE
shape_before = df.shape
print("Shape BEFORE transposing:", shape_before)

# 1) Set "Attribute" as index so each attribute becomes the row index
df = df.set_index("Attribute")
print("Shape after set_index('Attribute'):", df.shape)

# 2) Transpose so attributes become columns and planets become rows
df = df.T
print("Shape after transpose .T:", df.shape)

# 3) Name the index "Planet"
df.index.name = "Planet"
print("Index name:", df.index.name)

# 4) Reset index so "Planet" becomes its own column
df.reset_index(inplace=True)
print("Shape after reset_index:", df.shape)

# 5) Remove columns.name if set
df.columns.name = None

shape_after = df.shape
print("Final shape AFTER transposing:", shape_after)

display(df.head())

Shape BEFORE transposing: (20, 11)
Shape after set_index('Attribute'): (20, 10)
Shape after transpose .T: (10, 20)
Index name: Planet
Shape after reset_index: (10, 21)
Final shape AFTER transposing: (10, 21)

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No


**(c)** What each line of code does:
- `df = df.set_index("Attribute")`  
  Uses the `"Attribute"` column as the index. The labels in that column become row labels instead of a normal column.
- `df = df.T`  
  Transposes the DataFrame: rows become columns and columns become rows.
- `df.index.name = "Planet"`  
  Assigns the name `"Planet"` to the index so it’s clear that each row corresponds to a planet.
- `df.reset_index(inplace=True)`  
  Turns the index (`Planet`) back into a normal column called `"Planet"`, and creates a new default integer index.
- `df.columns.name = None`  
  Clears the name of the columns axis; purely cosmetic.

**(d)**   the original table’s structure is not exactly 11 planets by 20 attributes
- There might be extra rows that aren’t planets 
- Some attributes might not be planetary parameters, or there might be extra columns.  
So after transposing, the number of rows and columns is determined by whatever was actually in the original CSV, not just planets vs attributes

**(f)** 
- “Columns with units” are those whose names contain things like `(km)`, `(m/s^2)`, `(10^6 km)`, `(kg)`, `(days)`, `(deg)`
- “Columns without units” are dimensionless (like `Planet`, `Number of Moons`, `Ring System?`, `Global Magnetic Field?`, `Orbital eccentricity`).

In [4]:

print("Column names:\n")
print(df.columns.tolist())

cols_with_units = []
cols_without_units = []

for col in df.columns:
    if any(unit in col for unit in ["(", ")", "km", "kg", "m/s", "days", "deg"]):
        cols_with_units.append(col)
    else:
        cols_without_units.append(col)

print("\nColumns w/ units in their names:")
for col in cols_with_units:
    print("  -", col)

print("\nColumns that don't have units in their names:")
for col in cols_without_units:
    print("  -", col)

print("\nFull transposed DataFrame:")
display(df)

Column names:

['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']

Columns w/ units in their names:
  - Mass (10^24kg)
  - Diameter (km)
  - Density (kg/m^3)
  - Gravity (m/s^2)
  - Escape Velocity (km/s)
  - Rotation Period (hours)
  - Length of Day (hours)
  - Distance from Sun (10^6 km)
  - Perihelion (10^6 km)
  - Aphelion (10^6 km)
  - Orbital Period (days)
  - Orbital Velocity (km/s)
  - Orbital Inclination (deg)
  - Obliquity to Orbit (deg)
  - Mean Temperature (C)
  - Surface Pressure (bars)

Columns that don't have units in their names:
  - Planet
  - Orbital Eccentricity
  - Number of Moons
  - Ring System?
  - Global Magnetic Field?

Full transposed DataFrame:

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

In [5]:

print("Column dtypes from pandas:\n")
print(df.dtypes)

print("\nExample value types inside each column:\n")
for col in df.columns:
    print(f"Column: {col}")
    print(df[col].apply(type).value_counts(), "\n")

Column dtypes from pandas:

Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object

Example value types inside each column:

Column: Planet
Planet
<class 'str'>    10
Name: count, dtype: int64

Column: Mass (10^24kg)
Mass (10^24kg)
<class 'str'>    10
Name: count, dtype: int64

Column: Diameter (km)
Diameter (km)
<class 'str'>    10
Name: count, dtype: int64

Column: Density (kg/m^3)
Density (kg/m^3)
<class 'str'>    10
Name: count, dtype: int64

Column: Gravity (m/s^2)
Gravity (m/s^2)
<class 'str'>    10
Name: count, dtype: int64

Column: Escape Velocity (km/s)
Escape Velocity (km/s)
<class 'str'>    10
Name: count, dtype: int64

Column: Rotation Period (hours)
Rotation Period (hours)
<class 'str'>    10
Name: count, dtype: int64

Column: Length of Day (hours)
Length of Day (hours)
<class 'str'>    10
Name: count, dtype: int64

Column: Distance from Sun (10^6 km)
Distance from Sun (10^6 km)
<class 'str'>    10
Name: count, dtype: int64

Column: Perihelion (10^6 km)
Perihelion (10^6 km)
<class 'str'>    10
Name: count, dtype: int64

Column: Aphelion (10^6 km)
Aphelion (10^6 km)
<class 'str'>    10
Name: count, dtype: int64

Column: Orbital Period (days)
Orbital Period (days)
<class 'str'>    10
Name: count, dtype: int64

Column: Orbital Velocity (km/s)
Orbital Velocity (km/s)
<class 'str'>    10
Name: count, dtype: int64

Column: Orbital Inclination (deg)
Orbital Inclination (deg)
<class 'str'>    10
Name: count, dtype: int64

Column: Orbital Eccentricity
Orbital Eccentricity
<class 'str'>    10
Name: count, dtype: int64

Column: Obliquity to Orbit (deg)
Obliquity to Orbit (deg)
<class 'str'>    10
Name: count, dtype: int64

Column: Mean Temperature (C)
Mean Temperature (C)
<class 'str'>    10
Name: count, dtype: int64

Column: Surface Pressure (bars)
Surface Pressure (bars)
<class 'str'>    10
Name: count, dtype: int64

Column: Number of Moons
Number of Moons
<class 'str'>    10
Name: count, dtype: int64

Column: Ring System?
Ring System?
<class 'str'>    10
Name: count, dtype: int64

Column: Global Magnetic Field?
Global Magnetic Field?
<class 'str'>    10
Name: count, dtype: int64

## 2.1.2 

**(a)** 
From the `df[col].apply(type)` output, most entries are probably `<class 'str'>` (strings).  
After we convert, they will be numeric types like `float` or `int` for most columns.

**(b)** 
- You cannot do math directly on strings; `"10" + "5"` becomes `"105"`, not `15`.

In [6]:

non_numeric_cols = ["Planet", "Ring System?", "Global Magnetic Field?"]

for col in df.columns:
    if col not in non_numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")

print("New dtypes after conversion:\n")
print(df.dtypes)

object_columns = df.select_dtypes(include="object").columns.tolist()
print("\nColumns still of dtype 'object':", object_columns)

New dtypes after conversion:

Planet                          object
Mass (10^24kg)                 float64
Diameter (km)                    int64
Density (kg/m^3)                 int64
Gravity (m/s^2)                float64
Escape Velocity (km/s)         float64
Rotation Period (hours)        float64
Length of Day (hours)          float64
Distance from Sun (10^6 km)    float64
Perihelion (10^6 km)           float64
Aphelion (10^6 km)             float64
Orbital Period (days)          float64
Orbital Velocity (km/s)        float64
Orbital Inclination (deg)      float64
Orbital Eccentricity           float64
Obliquity to Orbit (deg)       float64
Mean Temperature (C)             int64
Surface Pressure (bars)        float64
Number of Moons                  int64
Ring System?                    object
Global Magnetic Field?          object
dtype: object

Columns still of dtype 'object': ['Planet', 'Ring System?', 'Global Magnetic Field?']

## 2.1.3 

**(a)** 
- `float64` – 64-bit floating point numbers  
- `int64` – 64-bit integers  
- `object` – general Python objects (often used for strings, or mixed types)

**(b)** 
- **float64**: decimal numbers with 64-bit precision.  
- **int64**: whole numbers with 64-bit precision.  
- **object**: a generic container type in pandas; can store strings or any Python object.

**(c)**   
They will be the non-numeric ones like:
- `Planet` — the names of the planets (strings)  
- `Ring System`  
- `Global Magnetic Field`

In [7]:

def attach_units(df, old_col, unit, new_col):
    numeric_values = pd.to_numeric(df[old_col], errors="coerce")
    
    quantities = numeric_values.values * unit
    
    df[new_col] = quantities
 
    df.drop(columns=[old_col], inplace=True)

    print(f"Attached units {unit} to column '{old_col}' → '{new_col}'")
    return df

In [8]:
from astropy import units as u

def attach_units(df, old_col, unit, new_col):
    
    new_values = []

    for val in df[old_col]:
        new_values.append(val * unit)

    df[old_col] = new_values

    df.rename(columns={old_col: new_col}, inplace=True)

In [9]:
unit    = 1e24 * u.kg
old_col = "Mass (10^24kg)"   
new_col = "Mass (kg)"

attach_units(df, old_col, unit, new_col)

df[["Planet", new_col]].head()

    Planet                 Mass (kg)
0  Mercury                3.3e+23 kg
1    Venus               4.87e+24 kg
2    Earth  5.969999999999999e+24 kg
3     Moon                7.3e+22 kg
4     Mars               6.42e+23 kg

In [10]:

peri_col = "Perihelion (10^6 km)"
aphe_col = "Aphelion (10^6 km)"

df["Perihelion (km)"] = df[peri_col].values * (1e6 * u.km)
df["Aphelion (km)"]   = df[aphe_col].values * (1e6 * u.km)

semi_major = (df["Perihelion (km)"] + df["Aphelion (km)"]) / 2

aphe_loc = df.columns.get_loc(aphe_col)
new_col_name = "Semi-major axis (km)"

df.insert(aphe_loc + 1, new_col_name, semi_major)

print("Column names after inserting semi-major axis:")
print(df.columns.tolist())

print("\nSemi-major axis column:")
print(df[["Planet", new_col_name]].head())

Column names after inserting semi-major axis:
['Planet', 'Mass (kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Semi-major axis (km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?', 'Perihelion (km)', 'Aphelion (km)']

Semi-major axis column:
    Planet  Semi-major axis (km)
0  Mercury            57900000.0
1    Venus           108200000.0
2    Earth           149600000.0
3     Moon              384500.0
4     Mars           228000000.0

In [11]:
orbital_period_col = "Orbital Period (days)"

period_days = df[orbital_period_col].values * u.day

period_years = period_days.to(u.year)

new_period_col = "Orbital Period (yr)"

df[new_period_col] = period_years
print("column names after converting orbital period:")
print(df.columns.tolist())

print("\nFull orbital period (yr) column:")
print(df[["Planet", new_period_col]])

favorite_planet ="Jupiter"
row = df[df["Planet"] == favorite_planet]

orbital_period = row[new_period_col].values[0]
print(f"\n{favorite_planet}'s orbital period is {orbital_period:.4f} yr")

column names after converting orbital period:
['Planet', 'Mass (kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Semi-major axis (km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?', 'Perihelion (km)', 'Aphelion (km)', 'Orbital Period (yr)']

Full orbital period (yr) column:
    Planet  Orbital Period (yr)
0  Mercury             0.240931
1    Venus             0.615195
2    Earth             0.999863
3     Moon             0.074743
4     Mars             1.880903
5  Jupiter            11.857632
6   Saturn            29.423682
7   Uranus            83.748118
8  Neptune           163.723477
9    Pluto           247.939767

Jupiter's orbital period is 11.8576 yr

## An AU is an astronomical unit which is defined as the distance from the earth to the sun, about 93 million miles. Or:

In [12]:
print("1 AU from astropy.constants:", const.au)

1 AU from astropy.constants:   Name   = Astronomical Unit
  Value  = 149597870700.0
  Uncertainty  = 0.0
  Unit  = m
  Reference = IAU 2012 Resolution B2

In [13]:
au_in_km = const.au.to(u.km)
print("How many km are in one AU? 1 AU in km:", au_in_km)

How many km are in one AU? 1 AU in km: 149597870.70000002 km

In [14]:
#I am having trouble saving it with the command in the homework...

import pandas as pd
from astropy import units as u

df_out = df.copy()

for col in df_out.columns:
    first = df_out[col].iloc[0]

    if isinstance(first, u.Quantity):
        df_out[col] = [x.value for x in df_out[col]]


df_out.to_csv("units.csv", index=False)
print("Saved units.csv successfully!")

UnitConversionError: '' (dimensionless) and 'km' (length) are not convertible